BEGIN;

ALTER TABLE "SW_TBL_CHARGE" DROP CONSTRAINT IF EXISTS "FK_CHARGE_DEFAULT_CHARGE";
ALTER TABLE "SW_TBL_KEYWORD_CHARGE" DROP CONSTRAINT IF EXISTS "FK_KEYWORD_CHARGE_CHARGE";
ALTER TABLE "SW_TBL_CHARGE_DETAILS" DROP CONSTRAINT IF EXISTS "FK_CHARGE_DETAILS_CHARGE";
DROP INDEX IF EXISTS "UQ_CHARGE_MAPPING_KEYWORD_CHARGE_ID";

COMMIT;
