BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_CHARGE_MAPPING_KEYWORD_CHARGE_ID"
  ON "SW_TBL_CHARGE_MAPPING" ("Keyword_Charge_Id")
  WHERE "Keyword_Charge_Id" IS NOT NULL;

ALTER TABLE "SW_TBL_CHARGE_DETAILS"
  ADD CONSTRAINT "FK_CHARGE_DETAILS_CHARGE"
  FOREIGN KEY ("Charge_ID")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID")
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "SW_TBL_KEYWORD_CHARGE"
  ADD CONSTRAINT "FK_KEYWORD_CHARGE_CHARGE"
  FOREIGN KEY ("Charge_Id")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID")
  ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "SW_TBL_CHARGE"
  ADD CONSTRAINT "FK_CHARGE_DEFAULT_CHARGE"
  FOREIGN KEY ("Def_Charge_ID")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID")
  ON UPDATE RESTRICT ON DELETE RESTRICT;

COMMIT;
