BEGIN;

DROP INDEX IF EXISTS "UQ_ACTIVE_DEFAULT_KEYWORD_CHARGE";
DROP INDEX IF EXISTS "UQ_ACTIVE_KEYWORD_CHARGE_LOOKUP";
ALTER TABLE "SW_TBL_KEYWORD_CHARGE" DROP CONSTRAINT IF EXISTS "FK_KEYWORD_CHARGE_MAPPING";
ALTER TABLE "SW_TBL_CHARGE" DROP CONSTRAINT IF EXISTS "FK_CHARGE_DEFAULT_CHARGE";
ALTER TABLE "SW_TBL_KEYWORD_CHARGE" DROP CONSTRAINT IF EXISTS "FK_KEYWORD_CHARGE_CHARGE";
ALTER TABLE "SW_TBL_CHARGE_DETAILS" DROP CONSTRAINT IF EXISTS "FK_CHARGE_DETAILS_CHARGE";
ALTER TABLE "SW_TBL_CHARGE_MAPPING" DROP CONSTRAINT IF EXISTS "UQ_CHARGE_MAPPING_KEYWORD_CHARGE_ID";

DELETE FROM "SW_TBL_KEYWORD_CHARGE";
DELETE FROM "SW_TBL_CHARGE_DETAILS";
DELETE FROM "SW_TBL_CHARGE_MAPPING";
DELETE FROM "SW_TBL_CHARGE";

INSERT INTO "SW_TBL_CHARGE" SELECT * FROM "MIG003_CHARGE_BACKUP";
INSERT INTO "SW_TBL_CHARGE_DETAILS" SELECT * FROM "MIG003_CHARGE_DETAILS_BACKUP";
INSERT INTO "SW_TBL_CHARGE_MAPPING" SELECT * FROM "MIG003_CHARGE_MAPPING_BACKUP";
INSERT INTO "SW_TBL_KEYWORD_CHARGE" SELECT * FROM "MIG003_KEYWORD_CHARGE_BACKUP";

SELECT setval(pg_get_serial_sequence('"SW_TBL_CHARGE"', 'ROW_ID'), (SELECT max("ROW_ID") FROM "SW_TBL_CHARGE"), true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_CHARGE_DETAILS"', 'Row_ID'), (SELECT max("Row_ID") FROM "SW_TBL_CHARGE_DETAILS"), true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_CHARGE_MAPPING"', 'RowId'), (SELECT max("RowId") FROM "SW_TBL_CHARGE_MAPPING"), true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_KEYWORD_CHARGE"', 'Row_Id'), (SELECT max("Row_Id") FROM "SW_TBL_KEYWORD_CHARGE"), true);

CREATE UNIQUE INDEX "UQ_CHARGE_MAPPING_KEYWORD_CHARGE_ID"
  ON "SW_TBL_CHARGE_MAPPING" ("Keyword_Charge_Id")
  WHERE "Keyword_Charge_Id" IS NOT NULL;
ALTER TABLE "SW_TBL_CHARGE_DETAILS"
  ADD CONSTRAINT "FK_CHARGE_DETAILS_CHARGE" FOREIGN KEY ("Charge_ID")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "SW_TBL_KEYWORD_CHARGE"
  ADD CONSTRAINT "FK_KEYWORD_CHARGE_CHARGE" FOREIGN KEY ("Charge_Id")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID") ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "SW_TBL_CHARGE"
  ADD CONSTRAINT "FK_CHARGE_DEFAULT_CHARGE" FOREIGN KEY ("Def_Charge_ID")
  REFERENCES "SW_TBL_CHARGE" ("Charge_ID") ON UPDATE RESTRICT ON DELETE RESTRICT;

DROP TABLE "MIG003_KEYWORD_CHARGE_BACKUP";
DROP TABLE "MIG003_CHARGE_MAPPING_BACKUP";
DROP TABLE "MIG003_CHARGE_DETAILS_BACKUP";
DROP TABLE "MIG003_CHARGE_BACKUP";

COMMIT;
