BEGIN;

CREATE INDEX IF NOT EXISTS "IDX_CHARGE_DETAILS_CHARGE_ID"
  ON "SW_TBL_CHARGE_DETAILS" ("Charge_ID");

CREATE INDEX IF NOT EXISTS "IDX_WALLET_WALLET_CODE"
  ON "SW_TBL_WALLET" ("Wallet_Code");

CREATE INDEX IF NOT EXISTS "IDX_CHARGE_MAPPING_ACTIVE_LOOKUP"
  ON "SW_TBL_CHARGE_MAPPING" ("Keyword_Charge_Id", "Status");

CREATE INDEX IF NOT EXISTS "IDX_KEYWORD_CHARGE_DEFAULT_LOOKUP"
  ON "SW_TBL_KEYWORD_CHARGE" ("Keyword", "Status", "Is_Default");

COMMIT;
