BEGIN;

DROP INDEX IF EXISTS "IDX_KEYWORD_CHARGE_DEFAULT_LOOKUP";
DROP INDEX IF EXISTS "IDX_CHARGE_MAPPING_ACTIVE_LOOKUP";
DROP INDEX IF EXISTS "IDX_WALLET_WALLET_CODE";
DROP INDEX IF EXISTS "IDX_CHARGE_DETAILS_CHARGE_ID";

COMMIT;
