BEGIN;

DROP INDEX IF EXISTS "IDX_KEYWORD_COMMISSION_DEFAULT";
DROP INDEX IF EXISTS "IDX_COMMISSION_DETAIL_ID";
DROP INDEX IF EXISTS "UQ_ACTIVE_KEYWORD_COMMISSION";
DROP INDEX IF EXISTS "UQ_COMMISSION_MAPPING_KEY";

ALTER TABLE "SW_TBL_COMMISSION" DROP CONSTRAINT IF EXISTS "FK_COMMISSION_DEFAULT";
ALTER TABLE "SW_TBL_KEYWORD_COMMISSION" DROP CONSTRAINT IF EXISTS "FK_KEYWORD_COMMISSION_COMMISSION";
ALTER TABLE "SW_TBL_COMMISSION_DETAIL" DROP CONSTRAINT IF EXISTS "FK_COMMISSION_DETAIL_COMMISSION";

DELETE FROM "SW_TBL_KEYWORD_COMMISSION";
DELETE FROM "SW_TBL_COMMISSION_DETAIL";
DELETE FROM "SW_TBL_COMMISSION_MAPPING";
DELETE FROM "SW_TBL_COMMISSION";

INSERT INTO "SW_TBL_COMMISSION" SELECT * FROM "MIG005_COMMISSION_BACKUP";
INSERT INTO "SW_TBL_COMMISSION_DETAIL" SELECT * FROM "MIG005_COMMISSION_DETAIL_BACKUP";
INSERT INTO "SW_TBL_COMMISSION_MAPPING" SELECT * FROM "MIG005_COMMISSION_MAPPING_BACKUP";
INSERT INTO "SW_TBL_KEYWORD_COMMISSION" SELECT * FROM "MIG005_KEYWORD_COMMISSION_BACKUP";

SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION"','ROW_ID'),COALESCE((SELECT max("ROW_ID") FROM "SW_TBL_COMMISSION"),1),EXISTS(SELECT 1 FROM "SW_TBL_COMMISSION"));
SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION_DETAIL"','Row_ID'),COALESCE((SELECT max("Row_ID") FROM "SW_TBL_COMMISSION_DETAIL"),1),EXISTS(SELECT 1 FROM "SW_TBL_COMMISSION_DETAIL"));
SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION_MAPPING"','RowId'),COALESCE((SELECT max("RowId") FROM "SW_TBL_COMMISSION_MAPPING"),1),EXISTS(SELECT 1 FROM "SW_TBL_COMMISSION_MAPPING"));
SELECT setval(pg_get_serial_sequence('"SW_TBL_KEYWORD_COMMISSION"','Row_ID'),COALESCE((SELECT max("Row_ID") FROM "SW_TBL_KEYWORD_COMMISSION"),1),EXISTS(SELECT 1 FROM "SW_TBL_KEYWORD_COMMISSION"));

DROP TABLE "MIG005_KEYWORD_COMMISSION_BACKUP";
DROP TABLE "MIG005_COMMISSION_MAPPING_BACKUP";
DROP TABLE "MIG005_COMMISSION_DETAIL_BACKUP";
DROP TABLE "MIG005_COMMISSION_BACKUP";

COMMIT;
