BEGIN;

CREATE TABLE "MIG005_COMMISSION_BACKUP" AS TABLE "SW_TBL_COMMISSION";
CREATE TABLE "MIG005_COMMISSION_DETAIL_BACKUP" AS TABLE "SW_TBL_COMMISSION_DETAIL";
CREATE TABLE "MIG005_COMMISSION_MAPPING_BACKUP" AS TABLE "SW_TBL_COMMISSION_MAPPING";
CREATE TABLE "MIG005_KEYWORD_COMMISSION_BACKUP" AS TABLE "SW_TBL_KEYWORD_COMMISSION";

DELETE FROM "SW_TBL_KEYWORD_COMMISSION";
DELETE FROM "SW_TBL_COMMISSION_DETAIL";
DELETE FROM "SW_TBL_COMMISSION_MAPPING";
UPDATE "SW_TBL_COMMISSION" SET "Def_Commission_ID" = NULL;
DELETE FROM "SW_TBL_COMMISSION";

INSERT INTO "SW_TBL_COMMISSION" ("Commission_ID","Description","Commission_Type","Expiry_On","Status","Def_Commission_ID","Created_By","Created_Date","Approved_By","Approved_Date","Distributor_Commission") VALUES
  (1,'PMNT fixed commission',0,NULL,1,NULL,'dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,0),
  (2,'SEND flexible commission',1,NULL,1,NULL,'dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,0);

INSERT INTO "SW_TBL_COMMISSION_DETAIL" ("Commission_ID","Comission_Type","Comission_Value","Start_Range","End_Range","Min_Comission","Max_Comission") VALUES
  (1,'Flat',5.00,0,999999999999.99,0,0),
  (2,'Flat',2.00,0,1000.00,0,0),
  (2,'Perc',0.50,1000.01,10000.00,5,50),
  (2,'Perc',0.25,10000.01,999999999999.99,25,250);

INSERT INTO "SW_TBL_COMMISSION_MAPPING" ("Keyword_Commission_Id","Description","Is_Default","Status","Created_By","Created_Date","Approved_By","Approved_Date","OperationType") VALUES
  (1,'Default PMNT commission',1,1,'dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,'I'),
  (2,'SEND wallet commission',0,1,'dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,'I');

INSERT INTO "SW_TBL_KEYWORD_COMMISSION" ("Keyword_Commission_ID","Keyword","Commission_ID","Description","Receiver","Created_BY","Created_Date","Approved_BY","Approved_Date","Is_Default","Commission_Map_Id","Status") VALUES
  (1,'PMNT',1,'Default PMNT source commission','S','dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,1,1,1),
  (2,'SEND',2,'SEND wallet 2 destination commission','D','dev_maker',CURRENT_TIMESTAMP,'dev_checker',CURRENT_TIMESTAMP,0,2,1);

SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION"','ROW_ID'),(SELECT max("ROW_ID") FROM "SW_TBL_COMMISSION"),true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION_DETAIL"','Row_ID'),(SELECT max("Row_ID") FROM "SW_TBL_COMMISSION_DETAIL"),true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_COMMISSION_MAPPING"','RowId'),(SELECT max("RowId") FROM "SW_TBL_COMMISSION_MAPPING"),true);
SELECT setval(pg_get_serial_sequence('"SW_TBL_KEYWORD_COMMISSION"','Row_ID'),(SELECT max("Row_ID") FROM "SW_TBL_KEYWORD_COMMISSION"),true);

ALTER TABLE "SW_TBL_COMMISSION_DETAIL" ADD CONSTRAINT "FK_COMMISSION_DETAIL_COMMISSION" FOREIGN KEY ("Commission_ID") REFERENCES "SW_TBL_COMMISSION"("Commission_ID") ON DELETE RESTRICT;
ALTER TABLE "SW_TBL_KEYWORD_COMMISSION" ADD CONSTRAINT "FK_KEYWORD_COMMISSION_COMMISSION" FOREIGN KEY ("Commission_ID") REFERENCES "SW_TBL_COMMISSION"("Commission_ID") ON DELETE RESTRICT;
ALTER TABLE "SW_TBL_COMMISSION" ADD CONSTRAINT "FK_COMMISSION_DEFAULT" FOREIGN KEY ("Def_Commission_ID") REFERENCES "SW_TBL_COMMISSION"("Commission_ID") ON DELETE RESTRICT;
CREATE UNIQUE INDEX "UQ_COMMISSION_MAPPING_KEY" ON "SW_TBL_COMMISSION_MAPPING"("Keyword_Commission_Id") WHERE "Keyword_Commission_Id" IS NOT NULL;
CREATE UNIQUE INDEX "UQ_ACTIVE_KEYWORD_COMMISSION" ON "SW_TBL_KEYWORD_COMMISSION"("Keyword","Commission_Map_Id") WHERE "Status"=1 AND "Is_Default"=0;
CREATE INDEX "IDX_COMMISSION_DETAIL_ID" ON "SW_TBL_COMMISSION_DETAIL"("Commission_ID");
CREATE INDEX "IDX_KEYWORD_COMMISSION_DEFAULT" ON "SW_TBL_KEYWORD_COMMISSION"("Keyword","Status","Is_Default");

COMMIT;
