BEGIN;

DELETE FROM public.reference_data_change_requests WHERE resource_type = 'AML';

ALTER TABLE public.reference_data_change_requests
  DROP CONSTRAINT IF EXISTS "CK_REFERENCE_CHANGE_RESOURCE";
ALTER TABLE public.reference_data_change_requests
  ADD CONSTRAINT "CK_REFERENCE_CHANGE_RESOURCE"
  CHECK (resource_type IN ('KEYWORD', 'WALLET_TYPE'));

DELETE FROM public."SW_TBL_AML"
WHERE "Created_By" = 'MIGRATION_010_TEST';

ALTER TABLE public."SW_TBL_AML"
  DROP CONSTRAINT IF EXISTS "UQ_AML_WALLET_KEYWORD",
  DROP CONSTRAINT IF EXISTS "FK_AML_WALLET_CODE",
  DROP CONSTRAINT IF EXISTS "FK_AML_KEYWORD",
  DROP CONSTRAINT IF EXISTS "CK_AML_POSITIVE_LIMITS",
  DROP CONSTRAINT IF EXISTS "CK_AML_AMOUNT_ORDER",
  DROP CONSTRAINT IF EXISTS "CK_AML_COUNT_ORDER";

ALTER TABLE public."SW_TBL_AML"
  DROP COLUMN IF EXISTS "Is_Active";

COMMIT;
