BEGIN;

DROP INDEX IF EXISTS public."IDX_CUSTOMER_WALLET_OWNER";
DROP INDEX IF EXISTS public."IDX_CUSTOMER_SCORE_PROFILE_LATEST";
DROP INDEX IF EXISTS public."IDX_CUSTOMER_REGISTRY_EMAIL_SEARCH";
DROP INDEX IF EXISTS public."IDX_CUSTOMER_REGISTRY_NAME_SEARCH";
DROP INDEX IF EXISTS public."IDX_CUSTOMER_REGISTRY_MSISDN_PREFIX";
DROP INDEX IF EXISTS public."IDX_CUSTOMER_REGISTRY_CREATED";

COMMIT;
