BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_REGISTRY_CREATED"
  ON public."SW_TBL_PROFILE_CUST"("Created_Date" DESC,"MSISDN" DESC);

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_REGISTRY_MSISDN_PREFIX"
  ON public."SW_TBL_PROFILE_CUST"(("MSISDN"::text) text_pattern_ops);

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_REGISTRY_NAME_SEARCH"
  ON public."SW_TBL_PROFILE_CUST"
  USING gin (
    lower(COALESCE("First_Name",'')||' '||COALESCE("Last_Name",''))
    gin_trgm_ops
  );

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_REGISTRY_EMAIL_SEARCH"
  ON public."SW_TBL_PROFILE_CUST"
  USING gin (lower(COALESCE("Email",'')) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_SCORE_PROFILE_LATEST"
  ON public.credit_scored_customers(profile_msisdn,updated_at DESC,_id DESC);

CREATE INDEX IF NOT EXISTS "IDX_CUSTOMER_WALLET_OWNER"
  ON public."SW_TBL_WALLET"(owner_msisdn)
  WHERE owner_type='CUSTOMER';

COMMIT;
