BEGIN;

DROP INDEX IF EXISTS public."IDX_TRANSACTION_REQUEST_REFERENCE_SEARCH";
DROP INDEX IF EXISTS public."IDX_TRANSACTION_REQUEST_STATE";
DROP INDEX IF EXISTS public."IDX_TRANSACTION_REQUEST_DEST_DATE";
DROP INDEX IF EXISTS public."IDX_TRANSACTION_REQUEST_SOURCE_DATE";
DROP INDEX IF EXISTS public."IDX_TRANSACTION_REQUEST_REGISTRY_DATE";

COMMIT;
