BEGIN;

DROP INDEX IF EXISTS public."UQ_CUSTOMER_MAIN_WALLET";
DROP INDEX IF EXISTS public."IDX_WALLET_OWNER_DEFAULT";
CREATE INDEX "IDX_WALLET_OWNER_DEFAULT"
  ON public."SW_TBL_WALLET"(owner_msisdn,currency,is_default)
  WHERE is_default AND "Status"<>6;

DROP INDEX IF EXISTS public."IDX_WALLET_SWIFT_BIC";
DROP INDEX IF EXISTS public."UQ_WALLET_IBAN";

ALTER TABLE public."SW_TBL_WALLET"
  DROP CONSTRAINT IF EXISTS "CK_WALLET_IBAN_FORMAT",
  DROP CONSTRAINT IF EXISTS "CK_WALLET_SWIFT_BIC_FORMAT";

-- Routing columns are retained on rollback to avoid destroying bank data.

COMMIT;
