BEGIN;

DROP INDEX IF EXISTS public."IDX_CUSTOMER_PROFILE_KYC_CASE";
ALTER TABLE public."SW_TBL_PROFILE_CUST"
  DROP CONSTRAINT IF EXISTS "FK_CUSTOMER_PROFILE_APPROVED_KYC_CASE",
  DROP COLUMN IF EXISTS "KYC_Verified_By",
  DROP COLUMN IF EXISTS "KYC_Verified_Date",
  DROP COLUMN IF EXISTS "KYC_Case_ID";

COMMIT;
