
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const LOGDB = 'LOGDB'
export const REDIS_CONNECTION = 'REDIS_CONNECTION'

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const TESTING_REPOSITORY='TESTING_REPOSITORY'
export const KEYWORD_REPOSITORY = 'KEYWORD_REPOSITORY';
export const WALLETDETAIL_REPOSITORY = 'WALLETDETAIL_REPOSITORY';
export const SW_VIEW_ALLUSER_REPOSITORY = 'SW_VIEW_ALLUSER_REPOSITORY';
export const TRANSACTION_REQUEST_REPOSITORY = 'TRANSACTION_REQUEST_REPOSITORY';
export const TRANSACTION_ENTRY_REPOSITORY = 'TRANSACTION_ENTRY_REPOSITORY';
